image: "phuxfu/a3s:a3s_debian_ansible"

stages:
  - ansible

ansible:
  stage: ansible
  script:
    # needed because ansible looks for python(2):
    - ln -s /usr/bin/python3 /usr/bin/python
    - /bin/bash -x ./tests/prepare.sh
    - echo "DEBUG"
    - cat /etc/sudoers
    - /usr/bin/id
    - /usr/bin/id foo
    - echo "DEBUG END"
    - sudo -u foo ansible-playbook --connection=local --inventory 127.0.0.1, tests/test.yml
