---
# install packages - from default repos and custom repos
- name: install packages
  apt:
    name:
    # packages from default OS-repos
    - ansible
    - tmux
    - git
    - gitk
    - gpg
    - keepassx
    - openjdk-8-jdk
    - bash-completion
    - vim
    - vim-common
    - ca-certificate
    - curl
    - apt-transport-https
    - lsb-release
    - gnupg
    - gnupg-agent
    - software-properties-common
    # packages from custom repos
    - azure-cli
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose
    state: present
    update_cache: yes
  become: yes
  tags: ['linux_workstation_configs']

- name: install helm binary
  copy:
    # currenty v. 3.0.0-beta.3
    src: binaries/helm
    dest: /usr/local/bin/helm
    mode: '0755'
    owner: root
    group: root
  become: yes
  tags: ['linux_workstation_configs']

- name: install terraform binary
  copy:
    # currenty v. 0.12.9
    src: binaries/terraform
    dest: /usr/local/bin/terraform
    mode: '0755'
    owner: root
    group: root
  become: yes
  tags: ['linux_workstation_configs']
