---
# instal aptitude first to be able to update the system
- name: install aptitude
  apt:
    name:
      - aptitude
    state: present
    update_cache: yes
  become: yes
  tags: ['linux_workstation_configs']

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
  become: yes
  tags: ['linux_workstation_configs']

# install packages - from default repos and custom repos
- name: install packages
  apt:
    name:
    # packages from default OS-repos
    - openssh-server
    - ansible
    - tmux
    - git
    - gitk
    - gpg
    - keepassx
    - openjdk-8-jdk
    - bash-completion
    - vim
    - vim-common
    - ca-certificates
    - curl
    - apt-transport-https
    - lsb-release
    - gnupg
    - gnupg-agent
    - software-properties-common
    - vpnc
    - nmap
    - guake
    - vagrant
    - powertop
    # packages from custom repos
    - azure-cli
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose
    - atom
    - virtualbox-6.1
    - kubectl
    state: present
    update_cache: yes
  become: yes
  tags: ['linux_workstation_configs']

- name: install helm binary
  copy:
    src: binaries/helm
    dest: /usr/local/bin/helm
    mode: '0755'
    owner: root
    group: root
  become: yes
  tags: ['linux_workstation_configs']

- name: install terraform binary
  copy:
    src: binaries/terraform
    dest: /usr/local/bin/terraform
    mode: '0755'
    owner: root
    group: root
  become: yes
  tags: ['linux_workstation_configs']


- name: install kubectx binary
  copy:
    src: binaries/kubectx
    dest: /usr/local/bin/kubectx
    mode: '0755'
    owner: root
    group: root
  become: yes
  tags: ['linux_workstation_configs']

- name: install kubens binary
  copy:
    src: binaries/kubens
    dest: /usr/local/bin/kubens
    mode: '0755'
    owner: root
    group: root
  become: yes
  tags: ['linux_workstation_configs']

- name: install minikube binary
  copy:
    src: binaries/minikube
    dest: /usr/local/bin/minikube
    mode: '0755'
    owner: root
    group: root
  become: yes
  tags: ['linux_workstation_configs']
