---
# install non-default repositories
- name: adding Microsoft gpg key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  become: yes
  tags: ['linux_workstation_configs']

- name: adding azure-cli repo
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ {{ ansible_lsb.codename }} main
    state: present
  become: yes
  tags: ['linux_workstation_configs']

- name: adding docker gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes
  tags: ['linux_workstation_configs']

- name: adding docker repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    state: present
  become: yes
  tags: ['linux_workstation_configs']

- name: adding atom gpg key
  apt_key:
    url: https://packagecloud.io/AtomEditor/atom/gpgkey
    state: present
  become: yes
  tags: ['linux_workstation_configs']

- name: adding atom repo
  apt_repository:
    repo: deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main
    state: present
  become: yes
  tags: ['linux_workstation_configs']

- name: adding virtualbox gpg key old
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox.asc
    state: present
  become: yes
  tags: ['linux_workstation_configs']

- name: adding virtualbox gpg key new
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present
  become: yes
  tags: ['linux_workstation_configs']

- name: adding virtualbox repo
  apt_repository:
    repo: deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian {{ ansible_lsb.codename }} contrib
    state: present
  become: yes
  tags: ['linux_workstation_configs']
