---
# install gpg
# instal aptitude first to be able to update the system
- name: install aptitude
  apt:
    name:
      - aptitude
    state: present
    update_cache: yes
  become: yes
  tags: ['linux_workstation_configs']

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
  become: yes
  tags: ['linux_workstation_configs']

- name: install gpg
  apt:
    name:
    # packages from default OS-repos
    - gpg
