---
# put configfiles to target host
- name: place atom_package_list
  copy:
    src: atom_package_list
    dest: {{ ansible_facts['env']['HOME'] }}/atom_package_list
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  tags: [linux_workstation_configs]

- name: place vimrc
  copy:
    src: vimrc
    dest: {{ ansible_facts['env']['HOME'] }}/.vimrc
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  tags: [linux_workstation_configs]

- name: place kubectl_autocompletion
  copy:
    src: kubectl_autocompletion
    dest: {{ ansible_facts['env']['HOME'] }}/.kubectl_autocompletion
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  tags: [linux_workstation_configs]

- name: place gitconfig
  template:
    src: gitconfig
    dest: {{ ansible_facts['env']['HOME'] }}/.gitconfig
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  tags: [linux_workstation_configs]
