---
# put configfiles to target host
- name: place atom_package_list
  copy:
    src: atom_package_list
    dest: /home/{{ ansible_user }}/atom_package_list
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  tags: [linux_workstation_configs]

- name: place vimrc
  copy:
    src: vimrc
    dest: /home/{{ ansible_user }}/.vimrc
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  tags: [linux_workstation_configs]

- name: place kubectl_autocompletion
  copy:
    src: kubectl_autocompletion
    dest: /home/{{ ansible_user }}/.kubectl_autocompletion
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  tags: [linux_workstation_configs]

- name: place gitconfig
  template:
    src: gitconfig
    dest: /home/{{ ansible_user }}/.gitconfig
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  tags: [linux_workstation_configs]
